version: '3.8'
services:
  app:
    container_name: survey-nestjs
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DB_HOST: db
    networks:
      - survey_network
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres:16.1-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - survey_network

volumes:
  postgres_data:

networks:
  survey_network: